my:
  nacos-namespace: 62d813f4-e610-4b31-8f87-24faeb0b8035
spring:
  application:
    name: swift-sail-geo-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: ${my.nacos-namespace}
      discovery:
        namespace: 62d813f4-e610-4b31-8f87-24faeb0b8035
      server-addr: 10.0.24.12:4090
      username: swiftSailDeveloper
      password: GiveMeACuteSister
  config:
    import:
      - nacos:${spring.application.name}-dev.yaml?refreshEnabled=true