name: CICD backend SwiftSail

on:
  push:
    branches: ["backend"]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print Java Version
        run: java --version

      - name: Say Hello
        run: echo "✅ GitHub Actions detected my deploy.yml!"
