name: CICD backend SwiftSail

on:
  push:
    branches: [ "backend" ]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: clone files
        uses: actions/checkout@v4

      - name: Maven clean and build gateway
        working-directory: ./backend/SwiftSail
        run: mvn clean package -pl gateway -am

      - name: stop last
        run: sudo systemctl stop swiftsail.gateway.service

      - name: Wait for process to exit
        run: timeout 10s bash -c 'while pgrep -f gateway-0.0.1-SNAPSHOT\.jar > /dev/null; do sleep 1; done' || true

      - name: remove last
        run: rm -rf /usr/swiftsail/target/gateway-0.0.1-SNAPSHOT.jar

      - name: move target
        working-directory: ./backend/SwiftSail
        run: mv gateway/target/gateway-0.0.1-SNAPSHOT.jar /usr/swiftsail/target/

      - name: who ami
        run: whoami

      - name: reload SwiftSail.gateway service
        run: sudo -n systemctl daemon-reload

      - name: restart SwiftSail.gateway service
        run: sudo -n systemctl restart swiftsail.gateway.service
